/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.javax.servlet.javax.servlet.api)
    api(libs.javax.mail.mail)
    api(libs.javax.mail.javax.mail.api)
    api(libs.mysql.mysql.connector.java)
    api(libs.org.jdbi.jdbi3.core)
    api(libs.commons.io.commons.io)
    api(libs.commons.fileupload.commons.fileupload)
    api(libs.com.google.code.gson.gson)
    api(libs.org.bouncycastle.bcpkix.jdk18on)
    testImplementation(libs.junit.junit)
}

group = "vn.edu.hcmuaf.fit"
version = "1.0-SNAPSHOT"
description = "BanBanhKem Maven Webapp"
java.sourceCompatibility = JavaVersion.VERSION_19

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
